/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Modele.Main;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ritch
 */
public class EmployeeAddRide extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeAddRide
     */
    public EmployeeAddRide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        AttractionNameTextField = new javax.swing.JTextField();
        FeaturesTextField = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        MailLabel = new javax.swing.JLabel();
        DateOfBirthLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        AvailabilityTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PriceTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setText("Add Ride");

        AttractionNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttractionNameTextFieldActionPerformed(evt);
            }
        });
        AttractionNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AttractionNameTextFieldKeyPressed(evt);
            }
        });

        FeaturesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeaturesTextFieldActionPerformed(evt);
            }
        });

        FirstNameLabel.setText("Attraction name");

        MailLabel.setText("Features");

        DateOfBirthLabel.setText("Availability");

        PasswordLabel.setText("Price (per ticket)");

        ConfirmButton.setBackground(new java.awt.Color(102, 204, 255));
        ConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        AvailabilityTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailabilityTextField1ActionPerformed(evt);
            }
        });
        AvailabilityTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AvailabilityTextField1KeyPressed(evt);
            }
        });

        jLabel1.setText("personns");

        jLabel2.setText("€");

        PriceTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(AvailabilityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MailLabel)
                            .addComponent(DateOfBirthLabel)
                            .addComponent(Title)
                            .addComponent(FirstNameLabel)
                            .addComponent(AttractionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FeaturesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(PriceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2))
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(FirstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AttractionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DateOfBirthLabel)
                .addGap(11, 11, 11)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvailabilityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FeaturesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PriceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(ConfirmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttractionNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttractionNameTextFieldActionPerformed

    }//GEN-LAST:event_AttractionNameTextFieldActionPerformed

    private void AttractionNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AttractionNameTextFieldKeyPressed

    }//GEN-LAST:event_AttractionNameTextFieldKeyPressed

    private void FeaturesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeaturesTextFieldActionPerformed

    }//GEN-LAST:event_FeaturesTextFieldActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        boolean success = true;

        String attractionName = AttractionNameTextField.getText();
        System.out.println(attractionName);
        int availability = Integer.parseInt(AvailabilityTextField1.getText());
        System.out.println(availability);
        
        String features = FeaturesTextField.getText();
        System.out.println(features);
        
        double price = Double.parseDouble(PriceTextField1.getText());
        System.out.println(price);

        if (attractionName.equals("")) {
            success = false;
            JOptionPane.showMessageDialog(null, "Missing Attraction name");
        } else if (availability == 0) {
            success = false;
            JOptionPane.showMessageDialog(null, "Wrong availability");
        } else if (features.equals("")) {
            success = false;
            JOptionPane.showMessageDialog(null, "Missing feature/description");
        } else if (price == 0) {
            success = false;
            JOptionPane.showMessageDialog(null, "Wrong price");
        }

        if (success == true) {
            //Constructor

            Connection com;

            try {
                com = DriverManager.getConnection(Main.url, Main.user, Main.password);

                //String sqlStatement = "INSERT INTO member (name, lastname, email, birth, password) "
                //+ "VALUES(" + m_fName + "," + m_lName + ",20," + m_mail + "," + m_password1 + ")";
                String sqlStatement = "INSERT INTO ride (name, availability, features, price, discount, image) "
                + "VALUES(?,?,?,?,?,?)";

                PreparedStatement pstmt = com.prepareStatement(sqlStatement);
                //java.util.Date ajdh = java.util.Calendar.getInstance().getTime();
                //System.out.println(ajdh);

                pstmt.setString(1, attractionName);
                pstmt.setInt(2, availability);
                pstmt.setString(3, features);
                pstmt.setDouble(4, price);
                pstmt.setInt(5, 0);
                pstmt.setString(6, "ride1");

                int rows = pstmt.executeUpdate();

                com.close();
                JOptionPane.showMessageDialog(null, "SUCCESS !\n" + attractionName + " HAS BEEN CREATED");
                EmployeeInterface empl = new EmployeeInterface();
                        empl.setVisible(true);
                dispose();
            } catch (SQLException e) {
                System.out.println("exception : " + e.getMessage());
                JOptionPane.showMessageDialog(null, "FAILURE IN RIDE CREATION");
            }

        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void AvailabilityTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailabilityTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvailabilityTextField1ActionPerformed

    private void AvailabilityTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AvailabilityTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvailabilityTextField1KeyPressed

    private void PriceTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAddRide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AttractionNameTextField;
    private javax.swing.JTextField AvailabilityTextField1;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JTextField FeaturesTextField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel MailLabel;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PriceTextField1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
