/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Modele.Main;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Etienne
 */
public class Pay extends javax.swing.JFrame {

    private double totalPrice;
    
    public Pay() {
        
        double a = 0.0;
        for(int i = 0 ; i< Main.AllResa.size() ; ++i)
        {
            totalPrice+= (Double) Main.AllResa.get(i).getPrix();          
        }
        totalPrice-=totalPrice*Main.connected.getDiscount();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel1 = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        TotalPriceLabel = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        CardNumberLabel = new javax.swing.JLabel();
        MasterCardRadioButton = new javax.swing.JRadioButton();
        VisaRadioButton = new javax.swing.JRadioButton();
        CBRadioButton = new javax.swing.JRadioButton();
        SecurityCodeFormattedTextField = new javax.swing.JFormattedTextField();
        ExpirationDateFormattedTextField = new javax.swing.JFormattedTextField();
        CardNumberFormattedTextField = new javax.swing.JFormattedTextField();
        SecurityCodeLabel = new javax.swing.JLabel();
        ExpirationDateLabel = new javax.swing.JLabel();
        CBImage = new javax.swing.JLabel();
        VisaImage = new javax.swing.JLabel();
        MasterCardImage = new javax.swing.JLabel();
        PayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(204, 204, 204));

        TotalLabel.setText("TOTAL :");

        TotalPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalPriceLabel.setForeground(new java.awt.Color(255, 102, 0));
        TotalPriceLabel.setText(totalPrice+" €");

        Panel2.setBackground(new java.awt.Color(255, 255, 255));

        CardNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CardNumberLabel.setText("Card Number : ");

        MasterCardRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(MasterCardRadioButton);

        VisaRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(VisaRadioButton);

        CBRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(CBRadioButton);
        CBRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRadioButtonActionPerformed(evt);
            }
        });

        try {
            SecurityCodeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ExpirationDateFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ExpirationDateFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpirationDateFormattedTextFieldActionPerformed(evt);
            }
        });

        try {
            CardNumberFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardNumberFormattedTextField.setToolTipText("");

        SecurityCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SecurityCodeLabel.setText("Security code : ");

        ExpirationDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExpirationDateLabel.setText("Expiration date : ");

        CBImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CarteBleue.jpg"))); // NOI18N

        VisaImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Visa.png"))); // NOI18N

        MasterCardImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MasterCard.png"))); // NOI18N

        PayButton.setText("Pay");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(CBRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(CBImage)
                        .addGap(18, 18, 18)
                        .addComponent(VisaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VisaImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(MasterCardRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MasterCardImage))
                    .addComponent(CardNumberLabel)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExpirationDateLabel)
                            .addComponent(SecurityCodeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExpirationDateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CardNumberFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecurityCodeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(PayButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VisaImage)
                            .addComponent(MasterCardImage)
                            .addComponent(CBImage)))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(CBRadioButton))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(MasterCardRadioButton))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(VisaRadioButton)))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNumberLabel)
                    .addComponent(CardNumberFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpirationDateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpirationDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecurityCodeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(PayButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalPriceLabel)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TotalPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExpirationDateFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpirationDateFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpirationDateFormattedTextFieldActionPerformed

    private void CBRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBRadioButtonActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here:
        Connection com;

        try {
            com = DriverManager.getConnection(Main.url, Main.user, Main.password);

                //String sqlStatement = "INSERT INTO member (name, lastname, email, birth, password) "
            //+ "VALUES(" + m_fName + "," + m_lName + ",20," + m_mail + "," + m_password1 + ")";
            for (int i = 0; i < Main.AllResa.size(); i++) {

                String sqlStatement = "INSERT INTO reservation (price, attractionName, mail, quantité, date) "
                        + "VALUES(?,?,?,?,?)";

                PreparedStatement pstmt = com.prepareStatement(sqlStatement);

                pstmt.setDouble(1, (double) Main.AllResa.get(i).getPrix());
                pstmt.setString(2, Main.AllResa.get(i).getNom());
                pstmt.setString(3, Main.AllResa.get(i).getLogin());
                
                String newDate = "";    //String we want
                String dayString = "";
                String MonthString = "";
                String YearString = "";
                int day, month, year;   //int buffer for the date

                day = Main.AllResa.get(i).getDate().getDate();
                
                if (day < 10) {
                    dayString = "0" + Integer.toString(day);

                } else {
                    dayString = Integer.toString(day);
                }              

                month = Main.AllResa.get(i).getDate().getMonth() + 1;

                if (month < 10) {
                    MonthString = "0" + Integer.toString(month);

                } else {
                    MonthString = Integer.toString(month);
                }

                year = Main.AllResa.get(i).getDate().getYear() + 1900;

                YearString = Integer.toString(year);

                newDate = dayString + "/" + MonthString + "/" + YearString;
                pstmt.setString(5, newDate);
                pstmt.setInt(4, Main.AllResa.get(i).getNombre());

                int rows = pstmt.executeUpdate();
            }

            com.close();

            Main.AllResa.clear();
            dispose();
            JOptionPane.showMessageDialog(null, "MERCI POUR VOTRE ACHAT");
            
        } catch (SQLException e) {
            System.out.println("exception : " + e.getMessage());
        }
    }//GEN-LAST:event_PayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CBImage;
    private javax.swing.JRadioButton CBRadioButton;
    private javax.swing.JFormattedTextField CardNumberFormattedTextField;
    private javax.swing.JLabel CardNumberLabel;
    private javax.swing.JFormattedTextField ExpirationDateFormattedTextField;
    private javax.swing.JLabel ExpirationDateLabel;
    private javax.swing.JLabel MasterCardImage;
    private javax.swing.JRadioButton MasterCardRadioButton;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JButton PayButton;
    private javax.swing.JFormattedTextField SecurityCodeFormattedTextField;
    private javax.swing.JLabel SecurityCodeLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JLabel VisaImage;
    private javax.swing.JRadioButton VisaRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
